# Generated by Django 4.1.3 on 2022-11-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='images/user-<django.db.models.fields.EmailField>'),
        ),
    ]
