# Generated by Django 4.1.3 on 2022-11-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='user-profile/user-<django.db.models.fields.EmailField>'),
        ),
    ]
